Message queue implementation
KinhTruongUnikie/IPC-methods-QNX pull request #4
Opened 2022-02-28 09:54 UTC by KinhTruongUnikie

The program can be run only with the combination of --help(optional), --queue <queue name> and --file <file name>(in any order), any other combinations will result exit error. 
The main implementation sits in ipc_methods.c.

P.S short option e.g -h -q also work

2022-02-28 10:13 UTC, RomainChaumontet approved these changes
Minor comments.

I am not a fan about according the size of the queue  to the size of the file.

The help command doesn't say specifically to give some argument after the --queue option.

2022-02-28 10:13 UTC, RomainChaumontet commented on C_hands_on_programming/ipc_methods.c
> +		exit(EXIT_FAILURE);
You shall free buffer before exiting (this comment is also available for the other EXIT_FAILURE)

2022-02-28 10:37 UTC, KinhTruongUnikie commented on C_hands_on_programming/ipc_methods.c
> +		exit(EXIT_FAILURE);
You are right, there are couple of places I overlooked the buffer not being freed, will fix that shortly

2022-02-28 10:50 UTC, baovu-unikie approved these changes

2022-02-28 12:13 UTC, ivan-estonia requested changes

2022-02-28 12:13 UTC, ivan-estonia commented on C_hands_on_programming/ipc_methods.c
> +	     free(buffer);
```
             perror("read\n");
	     free(buffer);
	     close(fd);
	     exit(EXIT_FAILURE);
	     ```

2022-02-28 12:13 UTC, ivan-estonia commented on C_hands_on_programming/ipc_methods.c
> +	     free(buffer);
`exit()` should be the last

2022-02-28 12:13 UTC, ivan-estonia commented on C_hands_on_programming/ipc_methods.c
> +		 write(fd, buffer, bytes);
/* TODO: error handler: bytes == -1 */

2022-02-28 12:13 UTC, ivan-estonia commented on C_hands_on_programming/ipc_methods.c
> +	while ((msg_queue = mq_open(info->argument_string, O_RDONLY)) == -1);
You should add a delay to this cycle or it will block the processor core.

2022-03-01 10:14 UTC, KinhTruongUnikie commented on C_hands_on_programming/ipc_methods.c
> +	     free(buffer);
Fixed now

2022-03-01 10:15 UTC, KinhTruongUnikie commented on C_hands_on_programming/ipc_methods.c
> +	     free(buffer);
Fixed

2022-03-01 10:15 UTC, KinhTruongUnikie commented on C_hands_on_programming/ipc_methods.c
> +		 write(fd, buffer, bytes);
Fixed

2022-03-01 10:20 UTC, ivan-estonia commented on C_hands_on_programming/ipc_methods.c
> +	     free(buffer);
`close(fd);`

2022-03-02 09:28 UTC, ivan-estonia approved these changes

2022-03-02 09:35 UTC, merged